site_name: Endless Horizons - RPG
repo_url: https://github.com/ehrpg
site_author: "@n0la, @johannes-z"
dev_addr: 127.0.0.1:8001

markdown_extensions:
  - admonition
  - toc:
      permalink: True

theme: readthedocs
extra_css:
    - css/extra.css
    - css/font-awesome.min.css
    - css/ehicons.css

markdown_extensions:
  - admonition
  - smarty
  - toc:
      permalink: True

pages:
- Introduction: 'index.md'
- Character Creation:
    - Overview: 'charactercreation/overview.md'
    - Abilities: 'charactercreation/abilities.md'
    - Secondary Abilities: 'charactercreation/secondary.md'
- Checks and Difficulties: 'checks.md'
- Skills:
    - Overview: 'skills/overview.md'
    - Available Skills: 'skills/skills.md'
- Perks:
    - Overview: 'perks/overview.md'
    - Available Perks: 'perks/perks.md'
- Backgrounds:
    - Overview: 'backgrounds/overview.md'
    - Available Backgrounds: 'backgrounds/backgrounds.md'
- Combat:
    - 'combat/overview.md'
    - Melee Combat: 'combat/melee.md'
    - Ranged Combat: 'combat/ranged.md'
    - Thrown Weapons: 'combat/thrown.md'
    - 'combat/damage.md'
- Injury and Death: 'injurydeath.md'
- Environmental Hazards: 'environment.md'
- Social Interactions: 'socialinteractions.md'
- Vessels:
    - Overview: 'vessels/overview.md'
    - Modules: 'vessels/modules.md'
    - Rooms: 'vessels/rooms.md'
    - Combat: 'vessels/combat.md'
    - Equipment: 'vessels/equipment.md'
    - Small Vessels: 'vessels/small.md'
    - Medium Vessels: 'vessels/medium.md'
- Equipment:
    - Overview: 'equipment/overview.md'
    - Firearms: 'equipment/firearms.md'
    - Apparel: 'equipment/apparel.md'
    - Explosives: 'equipment/explosives.md'
