site_name: Endless Horizons - RPG
repo_url: https://github.com/ehrpg
site_author: "@n0la, @johannes-z"
dev_addr: 0.0.0.0:8000

theme: readthedocs
extra_css: [extra.css]

pages:
- Introduction: 'index.md'
- Character Creation: 'charactercreation.md'
- Checks and Difficulties: 'checks.md'
- 'skills.md'
- 'perks.md'
- 'backgrounds.md'
- 'combat.md'
- Injury and Death: 'injurydeath.md'
- Environmental Hazards: 'environment.md'
- Social Interactions: 'socialinteractions.md'
- Vessel Overview: 'vessels.md'
- Vessel Combat: 'vesselcombat.md'
- Vessel Equipment: 'vesselequipment.md'
- Vessels: 'vessellist.md'
- 'equipment.md'
